name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-bash:
    name: ShellCheck & Bats
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck bats

      - name: ShellCheck
        run: shellcheck -x setup.sh scripts/*.sh

      - name: Run Bats tests
        run: bats tests

  lint-powershell:
    name: PSScriptAnalyzer
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Analyze PowerShell scripts
        shell: pwsh
        run: Invoke-ScriptAnalyzer -Path ./setup.ps1 -EnableExit
